id = "jump-to-native-ide"
name = "Jump to Native IDE"
version = "0.0.1"
schema_version = 1
authors = ["jasonli <jason@example.com>"]
description = "Jump to Xcode (xed) or Android Studio (studio) at the current file and line."
repository = "https://github.com/lijiaxin2333/zed2native-ide"
